# Generated by Django 4.2 on 2023-04-10 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemonAPI', '0004_remove_menuitem_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='littleLemonAPI.category'),
        ),
    ]
