# Generated by Django 4.2 on 2023-04-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemonAPI', '0005_menuitem_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category_id',
            new_name='category',
        ),
    ]
